#include config_base.yaml

script:
  log-directory: "/scratch/tgauweil/logs"
  body: |
         echo ${auto_args}

  parameters:
    input: "2470.nrrd"
    blockSize: 
        mask: ?x?x? # Defines as mask that is used to generate, here replace ? with elements out of range in val
        values: [2, 4]
    numSeeds: 10
    seedSet: 1
    stepSize: 0.1
    numMaxSteps: 1000
    distributeBlocks: simple

scheduler:
  type: slurm

  parameters:
    account: "tukl-taskvis"
    partition: "skylake-96"
    ntasks-per-node: 1
    cpus-per-task: 16
    mem: 1G
    time: 1:00:00
    nodes: 1
    mail-type: "NONE"